import type {
  Analysis,
  Finding,
  IndexRecord,
  MaintenanceRecord,
  Metric,
  PlanNode,
  QueryStat,
  Session,
} from "./types";

export const metrics: Metric[] = [
  {
    label: "Workload time",
    value: "2.84 s/s",
    detail: "Across 18.4k calls",
    trend: 12.4,
    tone: "cyan",
    points: [28, 34, 31, 42, 39, 51, 48, 55, 63, 58, 68, 72],
  },
  {
    label: "Cache hit ratio",
    value: "98.42%",
    detail: "Target ≥ 99%",
    trend: -0.7,
    tone: "violet",
    points: [80, 82, 84, 81, 79, 78, 76, 77, 74, 73, 71, 72],
  },
  {
    label: "Active sessions",
    value: "34",
    detail: "4 waiting · 2 blocked",
    trend: 8.1,
    tone: "amber",
    points: [18, 16, 22, 19, 24, 27, 23, 31, 28, 35, 31, 34],
  },
  {
    label: "Dead tuples",
    value: "4.1M",
    detail: "6.8% of live rows",
    trend: 4.2,
    tone: "rose",
    points: [32, 34, 36, 39, 41, 44, 47, 51, 55, 60, 65, 70],
  },
];

export const findings: Finding[] = [
  {
    id: "f-204",
    title: "Checkout lookup regressed 63%",
    description:
      "Mean execution time moved from 84 ms to 137 ms after the latest snapshot window.",
    severity: "critical",
    source: "Query regression",
    database: "commerce_prod",
    status: "open",
    firstSeen: "2h ago",
    lastSeen: "4m ago",
    occurrences: 7,
    href: "/queries/8839172",
    evidence: "p95 441 ms · 1.8k calls · +9.2 CPU min/hr",
  },
  {
    id: "f-199",
    title: "Autovacuum is falling behind on events",
    description:
      "Dead tuple ratio is above the table threshold and continues to climb.",
    severity: "warning",
    source: "Maintenance",
    database: "commerce_prod",
    status: "acknowledged",
    firstSeen: "8h ago",
    lastSeen: "4m ago",
    occurrences: 23,
    href: "/maintenance",
    evidence: "18.4% dead · last vacuum 17h ago · 2.4M dead rows",
  },
  {
    id: "f-191",
    title: "Two overlapping indexes on public.orders",
    description:
      "The wider index is a left-prefix match and carries measurable write cost.",
    severity: "info",
    source: "Index analysis",
    database: "commerce_prod",
    status: "open",
    firstSeen: "2d ago",
    lastSeen: "1h ago",
    occurrences: 4,
    href: "/indexes",
    evidence: "1.8 GB combined · 11.3M mutations/day",
  },
  {
    id: "f-188",
    title: "Stale statistics resolved on customers",
    description:
      "Autoanalyze completed and row-estimate accuracy returned to the healthy range.",
    severity: "success",
    source: "Maintenance",
    database: "analytics",
    status: "resolved",
    firstSeen: "3d ago",
    lastSeen: "1d ago",
    occurrences: 2,
    href: "/maintenance",
    evidence: "Estimate error 1.08× · analyzed 1d ago",
  },
];

export const queries: QueryStat[] = [
  {
    id: "8839172",
    query:
      "SELECT o.id, o.total, c.email FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.store_id = $1 AND o.status = $2 ORDER BY o.created_at DESC LIMIT $3",
    database: "commerce_prod",
    user: "app_reader",
    calls: 1842,
    totalTime: 252354,
    meanTime: 137.0,
    rows: 46120,
    cacheHit: 91.2,
    tempIo: "1.8 GB",
    wal: "0 B",
    delta: 63.1,
    status: "regressed",
    tables: ["public.orders", "public.customers"],
    points: [42, 45, 40, 49, 51, 54, 72, 79, 82, 91, 98, 100],
  },
  {
    id: "1224589",
    query:
      "SELECT date_trunc($1, created_at), count(*), sum(total) FROM orders WHERE created_at >= $2 GROUP BY 1 ORDER BY 1",
    database: "commerce_prod",
    user: "reporting",
    calls: 386,
    totalTime: 101343,
    meanTime: 262.5,
    rows: 9264,
    cacheHit: 96.8,
    tempIo: "418 MB",
    wal: "0 B",
    delta: 18.6,
    status: "regressed",
    tables: ["public.orders"],
    points: [58, 62, 60, 55, 64, 67, 65, 72, 77, 73, 80, 84],
  },
  {
    id: "4419021",
    query:
      "SELECT p.id, p.title, ts_rank(p.search_vector, websearch_to_tsquery($1)) AS rank FROM products p WHERE p.search_vector @@ websearch_to_tsquery($1) ORDER BY rank DESC LIMIT $2",
    database: "commerce_prod",
    user: "app_reader",
    calls: 9274,
    totalTime: 81014,
    meanTime: 8.73,
    rows: 183881,
    cacheHit: 99.7,
    tempIo: "0 B",
    wal: "0 B",
    delta: -12.3,
    status: "improved",
    tables: ["catalog.products"],
    points: [72, 69, 66, 61, 63, 58, 54, 51, 49, 45, 43, 40],
  },
  {
    id: "7841102",
    query:
      "SELECT * FROM inventory_reservations WHERE expires_at < now() AND released_at IS NULL FOR UPDATE SKIP LOCKED LIMIT $1",
    database: "commerce_prod",
    user: "worker",
    calls: 41429,
    totalTime: 70200,
    meanTime: 1.69,
    rows: 82858,
    cacheHit: 99.9,
    tempIo: "0 B",
    wal: "22 MB",
    delta: 1.2,
    status: "stable",
    tables: ["public.inventory_reservations"],
    points: [49, 50, 48, 51, 52, 50, 49, 52, 51, 53, 52, 53],
  },
  {
    id: "5521108",
    query:
      "SELECT tenant_id, event_type, count(*) FROM audit.events WHERE occurred_at BETWEEN $1 AND $2 GROUP BY tenant_id, event_type",
    database: "analytics",
    user: "analyst",
    calls: 94,
    totalTime: 65414,
    meanTime: 695.9,
    rows: 147028,
    cacheHit: 88.4,
    tempIo: "3.2 GB",
    wal: "0 B",
    delta: 4.8,
    status: "stable",
    tables: ["audit.events"],
    points: [58, 56, 60, 61, 59, 63, 64, 62, 66, 65, 67, 68],
  },
];

export const indexes: IndexRecord[] = [
  {
    name: "orders_store_status_created_idx",
    table: "orders",
    schema: "public",
    size: "1.24 GB",
    scans: 928143,
    type: "btree",
    status: "healthy",
    writeCost: "high",
    definition:
      "CREATE INDEX ON public.orders (store_id, status, created_at DESC)",
  },
  {
    name: "orders_store_status_idx",
    table: "orders",
    schema: "public",
    size: "742 MB",
    scans: 11,
    type: "btree",
    status: "overlap",
    writeCost: "high",
    definition: "CREATE INDEX ON public.orders (store_id, status)",
  },
  {
    name: "orders_customer_id_idx",
    table: "orders",
    schema: "public",
    size: "618 MB",
    scans: 48190,
    type: "btree",
    status: "healthy",
    writeCost: "medium",
    definition: "CREATE INDEX ON public.orders (customer_id)",
  },
  {
    name: "events_occurred_at_brin",
    table: "events",
    schema: "audit",
    size: "3.8 MB",
    scans: 849,
    type: "brin",
    status: "healthy",
    writeCost: "low",
    definition: "CREATE INDEX USING brin ON audit.events (occurred_at)",
  },
  {
    name: "customers_legacy_ref_idx",
    table: "customers",
    schema: "public",
    size: "182 MB",
    scans: 0,
    type: "btree",
    status: "unused",
    writeCost: "medium",
    definition: "CREATE INDEX ON public.customers (legacy_ref)",
  },
  {
    name: "products_search_vector_idx",
    table: "products",
    schema: "catalog",
    size: "2.1 GB",
    scans: 2384190,
    type: "gin",
    status: "healthy",
    writeCost: "medium",
    definition: "CREATE INDEX USING gin ON catalog.products (search_vector)",
  },
];

export const maintenance: MaintenanceRecord[] = [
  {
    table: "events",
    schema: "audit",
    totalSize: "48.2 GB",
    liveRows: 10582913,
    deadRows: 2391492,
    deadRatio: 18.4,
    lastVacuum: "17h ago",
    lastAnalyze: "2h ago",
    freezeAge: 288_409_124,
    risk: "high",
  },
  {
    table: "orders",
    schema: "public",
    totalSize: "31.4 GB",
    liveRows: 42420918,
    deadRows: 948221,
    deadRatio: 2.2,
    lastVacuum: "3h ago",
    lastAnalyze: "42m ago",
    freezeAge: 92_118_204,
    risk: "medium",
  },
  {
    table: "inventory_reservations",
    schema: "public",
    totalSize: "8.7 GB",
    liveRows: 8214221,
    deadRows: 602912,
    deadRatio: 6.8,
    lastVacuum: "6h ago",
    lastAnalyze: "3h ago",
    freezeAge: 48_902_121,
    risk: "medium",
  },
  {
    table: "customers",
    schema: "public",
    totalSize: "11.2 GB",
    liveRows: 12800921,
    deadRows: 28111,
    deadRatio: 0.2,
    lastVacuum: "1h ago",
    lastAnalyze: "1d ago",
    freezeAge: 18_410_920,
    risk: "low",
  },
  {
    table: "products",
    schema: "catalog",
    totalSize: "19.6 GB",
    liveRows: 2091821,
    deadRows: 21092,
    deadRatio: 1,
    lastVacuum: "48m ago",
    lastAnalyze: "48m ago",
    freezeAge: 12_428_123,
    risk: "low",
  },
];

export const sessions: Session[] = [
  {
    pid: 20418,
    database: "commerce_prod",
    user: "reporting",
    application: "metabase",
    client: "10.0.4.81",
    state: "active",
    wait: "Lock · transactionid",
    duration: "03:42",
    query:
      "UPDATE daily_store_rollups SET revenue = $1 WHERE store_id = $2 AND day = $3",
    blockedBy: 20391,
  },
  {
    pid: 20391,
    database: "commerce_prod",
    user: "app_writer",
    application: "checkout-api",
    client: "10.0.2.14",
    state: "idle in transaction",
    wait: "Client · ClientRead",
    duration: "08:17",
    query: "UPDATE orders SET status = $1 WHERE id = $2",
  },
  {
    pid: 20492,
    database: "commerce_prod",
    user: "app_reader",
    application: "storefront",
    client: "10.0.3.92",
    state: "active",
    wait: "IO · DataFileRead",
    duration: "00:41",
    query: queries[0]!.query,
  },
  {
    pid: 20501,
    database: "analytics",
    user: "analyst",
    application: "psql",
    client: "172.20.0.8",
    state: "active",
    wait: "—",
    duration: "01:22",
    query: queries[4]!.query,
  },
  {
    pid: 20511,
    database: "commerce_prod",
    user: "worker",
    application: "inventory-worker",
    client: "10.0.5.12",
    state: "idle",
    wait: "Client · ClientRead",
    duration: "00:03",
    query: "COMMIT",
  },
];

export const plan: PlanNode = {
  id: "root",
  name: "Limit",
  time: 137.02,
  cost: 99.9,
  rows: 25,
  estimate: 25,
  loops: 1,
  tone: "warning",
  detail: "Returns 25 rows after sorting the joined result.",
  children: [
    {
      id: "sort",
      name: "Sort",
      time: 136.98,
      cost: 99.1,
      rows: 25,
      estimate: 492,
      loops: 1,
      tone: "critical",
      detail: "Top-N heapsort · 38 kB memory · 19.7× estimate error",
      children: [
        {
          id: "loop",
          name: "Nested Loop",
          time: 132.41,
          cost: 91.8,
          rows: 2219,
          estimate: 492,
          loops: 1,
          tone: "warning",
          detail:
            "4.5× more rows than estimated; inner scan repeated 2,219 times.",
          children: [
            {
              id: "orders",
              name: "Bitmap Heap Scan",
              relation: "public.orders",
              time: 88.72,
              cost: 61.5,
              rows: 2219,
              estimate: 492,
              loops: 1,
              tone: "critical",
              detail: "14,821 heap blocks read · 82% of shared I/O",
            },
            {
              id: "customers",
              name: "Index Scan",
              relation: "public.customers",
              time: 0.018,
              cost: 30.3,
              rows: 1,
              estimate: 1,
              loops: 2219,
              tone: "info",
              detail: "customers_pkey · 2,219 loops · 98.7% cache hit",
            },
          ],
        },
      ],
    },
  ],
};

export const analyses: Analysis[] = [
  {
    id: "a-29",
    title: "Checkout query regression",
    queryId: "8839172",
    model: "gpt-5.6-terra",
    createdAt: "12m ago",
    severity: "critical",
    confidence: 94,
    summary:
      "The plan is reading far more order pages than necessary and compounds the cost with estimate error before the final sort.",
    requestId: "req_2d8f…91aa",
    tokens: 3182,
  },
  {
    id: "a-28",
    title: "Events aggregation review",
    queryId: "5521108",
    model: "gpt-5.6-sol",
    createdAt: "4h ago",
    severity: "warning",
    confidence: 87,
    summary:
      "The existing BRIN index narrows time ranges efficiently, but the grouping spill suggests increasing work_mem for this reporting role or pre-aggregation.",
    requestId: "req_eb30…9af1",
    tokens: 4204,
  },
  {
    id: "a-27",
    title: "Legacy customer index",
    queryId: "—",
    model: "gpt-5.6-terra",
    createdAt: "1d ago",
    severity: "info",
    confidence: 78,
    summary:
      "Removal is plausible after a full business-cycle observation window, but zero scans alone is insufficient evidence.",
    requestId: "req_10e4…8b2d",
    tokens: 1812,
  },
];

export const capabilities = [
  {
    label: "pg_stat_statements",
    status: "Available",
    detail: "v1.11 · full query text",
  },
  {
    label: "pg_read_all_stats",
    status: "Available",
    detail: "Granted to observer",
  },
  {
    label: "pgstattuple",
    status: "Unavailable",
    detail: "Exact bloat checks disabled",
  },
  {
    label: "Track I/O timing",
    status: "Available",
    detail: "track_io_timing = on",
  },
  {
    label: "HypoPG",
    status: "Unavailable",
    detail: "Suggestions are evidence-only",
  },
];

export const demoRepository = {
  metrics: () => metrics,
  findings: () => findings,
  queries: () => queries,
  query: (id: string) =>
    queries.find((query) => query.id === id) ?? queries[0]!,
  indexes: () => indexes,
  maintenance: () => maintenance,
  sessions: () => sessions,
  plan: () => plan,
  analyses: () => analyses,
  capabilities: () => capabilities,
};
